# MPI-based Makefile using mpic++ and mpicc.

# Define a directory to use as local disk.
LOCALDISK = .

CC =		mpic++ -m64
CCFLAGS =	-g -O 
DEPFLAGS =	-M
ARCHIVE =	ar
ARFLAGS =	-rc

include Makefile.common

