# APP multiple-machine Makefile with explicit file list

SHELL = /bin/sh

# Definitions

ROOT =	lmp
EXE =	$(ROOT)_$@

SRC =	app.cpp error.cpp input.cpp library.cpp main.cpp memory.cpp shell.cpp timer.cpp universe.cpp variable.cpp

INC =	app.h error.h input.h library.h memory.h pointers.h shell.h timer.h universe.h variable.h

OBJ = 	$(SRC:.cpp=.o)

# Targets

help:
	@echo 'Type "make target" where target is one of:'
	@echo ''
	@files="`ls MAKE/Makefile.*`"; \
	for file in $$files; do head -1 $$file; done

clean:
	rm -rf Obj_*

.DEFAULT:
	@test -f MAKE/Makefile.$@
	@if [ ! -d Obj_$@ ]; then mkdir Obj_$@; fi
	@cp -p $(SRC) $(INC) Obj_$@
	@cp MAKE/Makefile.$@ Obj_$@/Makefile
	@cd Obj_$@; \
	$(MAKE) $(MFLAGS) "OBJ = $(OBJ)" "INC = $(INC)" "EXE = ../$(EXE)" ../$(EXE)
	@if [ -d Obj_$@ ]; then cd Obj_$@; rm -f $(SRC) $(INC) Makefile*; fi
