# Makefile for PHISH apps

CC =		/opt/openmpi-gnu-1.3.2/bin/mpiCC
CCFLAGS =	-O
LINK =		/opt/openmpi-gnu-1.3.2/bin/mpiCC
LINKFLAGS =	-O 
LIB =		libphish.a
SYSLIB =	
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# PHISH SPs and stand-alone programs

include Makefile.common

# Clean

clean:
	@rm -f *.o

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
