# Makefile for PHISH library

CC =		/opt/openmpi-gnu-1.3.2/bin/mpiCC
CCFLAGS =	-O
LINK =		/opt/openmpi-gnu-1.3.2/bin/mpiCC
LINKFLAGS =	-O 
LIB =		libphish.a
SYSLIB =	
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# PHISH library

phish:	phish.o hash.o
	$(ARCHIVE) $(ARFLAGS) libphish.a phish.o hash.o

clean:
	@rm -f *.o
	@rm -f libphish.a

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
