# Makefile for PHISH apps

CC =		mpic++
CCFLAGS =	-g -O -DMPICH_IGNORE_CXX_SEEK -I../src
LINK =		mpic++
LINKFLAGS =	-g -O 
LIB =		../src/libphish.a
SYSLIB =
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# PHISH SPs and stand-alone programs

include Makefile.common

# Clean

clean:
	@rm -f *.o

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
