# Mac/MPI Makefile for MapReduce programs

CC =		mpic++ 
CCFLAGS =	-g -I../new
CCFLAGS += -DNEW_OUT_OF_CORE
LINK =		mpic++ 
LINKFLAGS =	-g 
LINKFLAGS += -DNEW_OUT_OF_CORE
USRLIB =	-L../new -lmrmpi
SYSLIB =	
LIB =		../new/libmrmpi.a


include Makefile.common

