# Mac/MPI Makefile for MapReduce programs

CC =		mpic++ -m64
CCFLAGS =	-g -I../src -Wall 
CCFLAGS +=	-DNEW_OUT_OF_CORE
#CCFLAGS +=	-DNOISY 
#CCFLAGS +=	-DKDDTIME 
LINK =		mpic++ -m64
LINKFLAGS =	-g
USRLIB =	-L../src -lmrmpi 
SYSLIB =	
LIB =		../src/libmrmpi.a
DEPFLAGS =      -M


SRC = 		mrvector.cpp mrmatrix.cpp 
OBJS = 		$(SRC:.cpp=.o)

include Makefile.common

