# Mac/MPI Makefile for MapReduce programs

CC =		mpic++ -m64
CCFLAGS =	-g -I../src
#CCFLAGS += -DNEW_OUT_OF_CORE
LINK =		mpic++ -m64
LINKFLAGS =	-g 
#LINKFLAGS += -DNEW_OUT_OF_CORE
USRLIB =	-L../src -lmrmpi
SYSLIB =	
LIB =		../src/libmrmpi.a
DEPFLAGS = -M

include Makefile.common

