# Mac/MPI Makefile for MapReduce programs

CC =		mpic++ 
CCFLAGS =	-g -I../src  
#CCFLAGS += -DNEW_OUT_OF_CORE
LINK =		mpic++ 
LINKFLAGS =	-g 
#LINKFLAGS += -DNEW_OUT_OF_CORE
USRLIB =	-L../src -lmrmpi
SYSLIB =	
LIB =		../src/libmrmpi.a


include Makefile.common

