# Linux/MPI Makefile for MapReduce programs

CC =		g++
CCFLAGS =	-g -O -I../new  -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O 
USRLIB =	-L../new -lmrmpi
SYSLIB =	-lmpich -lpthread -lrt
DEPFLAGS = 	-M

LIB =		../new/libmrmpi.a

include Makefile.common
