# Linux/MPI Makefile for MapReduce programs

CC =		g++
CCFLAGS =	-g -O -I../src  -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O 
USRLIB =	-L../src -lmrmpi
SYSLIB =	-lmpich -lpthread -lrt
DEPFLAGS = 	-M

LIB =		../src/libmrmpi.a

include Makefile.common
