# Tbird Makefile for MapReduce tools

CC =		mpic++ 
CCFLAGS =	-O2 -I../new
#CCFLAGS +=     -DKDDTIME

LINK =		mpic++
LINKFLAGS =	-O2 -L../new -lmrmpi
USRLIB =	-L../new -lmrmpi
SYSLIB =	
LIB =		../new/libmrmpi.a
DEPFLAGS =      -M


include Makefile.common
