# Red Storm (reddish) Makefile for MapReduce programs

CC =		CC
CCFLAGS =	-fastsse -I../src -DMPICH_IGNORE_CXX_SEEK
LINK =		CC
LINKFLAGS =	-O  
USRLIB =	-L../src -lmrmpi
SYSLIB =
DEPFLAGS =      -M


include Makefile.common
