# Mac/MPI Makefile for MapReduce tools

CC =		mpic++ -m64
#CCFLAGS =	-g -O -I../src 
CCFLAGS =	-g  -I../src 
LINK =		mpic++ -m64
#LINKFLAGS =	-g -O -L../src -lmrmpi
LINKFLAGS =	-g  -L../src -lmrmpi
USRLIB =	
SYSLIB =	

LIB =		../src/libmrmpi.a

# Targets

all:	matvec

matvec:	matvec.o $(LIB)
	$(LINK) $(LINKFLAGS) matvec.o $(USRLIB) $(SYSLIB) -o matvec

clean:
	rm *.o
	rm matvec

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
